/**
 *  Copyright (c) 2021 CentraleSupélec.
 *  This program and the accompanying materials are made
 *  available under the terms of the Apache License version 2.0
 *  which accompanies this distribution, and is available at
 *  http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Contributors:
 *      Computer Science Department, CentraleSupélec
 *  Contacts:
 *      dominique.marcadet@centralesupelec.fr
 *  Web site:
 *      https://github.com/marcadetd/javaparser.ecore
 * 
 */
package fr.centralesupelec.csd.ejava.provider;

import fr.centralesupelec.csd.ejava.util.EJavaAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class EJavaItemProviderAdapterFactory extends EJavaAdapterFactory
        implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected Collection< Object > supportedTypes = new ArrayList< Object >();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public EJavaItemProviderAdapterFactory() {
        supportedTypes.add( IEditingDomainItemProvider.class );
        supportedTypes.add( IStructuredItemContentProvider.class );
        supportedTypes.add( ITreeItemContentProvider.class );
        supportedTypes.add( IItemLabelProvider.class );
        supportedTypes.add( IItemPropertySource.class );
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ArrayCreationLevel} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ArrayCreationLevelItemProvider arrayCreationLevelItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ArrayCreationLevel}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createArrayCreationLevelAdapter() {
        if( arrayCreationLevelItemProvider == null ) {
            arrayCreationLevelItemProvider = new ArrayCreationLevelItemProvider( this );
        }

        return arrayCreationLevelItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.CompilationUnit} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CompilationUnitItemProvider compilationUnitItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.CompilationUnit}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCompilationUnitAdapter() {
        if( compilationUnitItemProvider == null ) {
            compilationUnitItemProvider = new CompilationUnitItemProvider( this );
        }

        return compilationUnitItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ImportDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ImportDeclarationItemProvider importDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ImportDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createImportDeclarationAdapter() {
        if( importDeclarationItemProvider == null ) {
            importDeclarationItemProvider = new ImportDeclarationItemProvider( this );
        }

        return importDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.PackageDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PackageDeclarationItemProvider packageDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.PackageDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createPackageDeclarationAdapter() {
        if( packageDeclarationItemProvider == null ) {
            packageDeclarationItemProvider = new PackageDeclarationItemProvider( this );
        }

        return packageDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.AnnotationDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AnnotationDeclarationItemProvider annotationDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.AnnotationDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAnnotationDeclarationAdapter() {
        if( annotationDeclarationItemProvider == null ) {
            annotationDeclarationItemProvider = new AnnotationDeclarationItemProvider( this );
        }

        return annotationDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.AnnotationMemberDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AnnotationMemberDeclarationItemProvider annotationMemberDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.AnnotationMemberDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAnnotationMemberDeclarationAdapter() {
        if( annotationMemberDeclarationItemProvider == null ) {
            annotationMemberDeclarationItemProvider = new AnnotationMemberDeclarationItemProvider( this );
        }

        return annotationMemberDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ClassOrInterfaceDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ClassOrInterfaceDeclarationItemProvider classOrInterfaceDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ClassOrInterfaceDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createClassOrInterfaceDeclarationAdapter() {
        if( classOrInterfaceDeclarationItemProvider == null ) {
            classOrInterfaceDeclarationItemProvider = new ClassOrInterfaceDeclarationItemProvider( this );
        }

        return classOrInterfaceDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ConstructorDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ConstructorDeclarationItemProvider constructorDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ConstructorDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createConstructorDeclarationAdapter() {
        if( constructorDeclarationItemProvider == null ) {
            constructorDeclarationItemProvider = new ConstructorDeclarationItemProvider( this );
        }

        return constructorDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.EnumConstantDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected EnumConstantDeclarationItemProvider enumConstantDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.EnumConstantDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createEnumConstantDeclarationAdapter() {
        if( enumConstantDeclarationItemProvider == null ) {
            enumConstantDeclarationItemProvider = new EnumConstantDeclarationItemProvider( this );
        }

        return enumConstantDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.EnumDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected EnumDeclarationItemProvider enumDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.EnumDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createEnumDeclarationAdapter() {
        if( enumDeclarationItemProvider == null ) {
            enumDeclarationItemProvider = new EnumDeclarationItemProvider( this );
        }

        return enumDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.FieldDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FieldDeclarationItemProvider fieldDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.FieldDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFieldDeclarationAdapter() {
        if( fieldDeclarationItemProvider == null ) {
            fieldDeclarationItemProvider = new FieldDeclarationItemProvider( this );
        }

        return fieldDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.InitializerDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InitializerDeclarationItemProvider initializerDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.InitializerDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInitializerDeclarationAdapter() {
        if( initializerDeclarationItemProvider == null ) {
            initializerDeclarationItemProvider = new InitializerDeclarationItemProvider( this );
        }

        return initializerDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.MethodDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected MethodDeclarationItemProvider methodDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.MethodDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createMethodDeclarationAdapter() {
        if( methodDeclarationItemProvider == null ) {
            methodDeclarationItemProvider = new MethodDeclarationItemProvider( this );
        }

        return methodDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.Parameter} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ParameterItemProvider parameterItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.Parameter}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createParameterAdapter() {
        if( parameterItemProvider == null ) {
            parameterItemProvider = new ParameterItemProvider( this );
        }

        return parameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ReceiverParameter} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ReceiverParameterItemProvider receiverParameterItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ReceiverParameter}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createReceiverParameterAdapter() {
        if( receiverParameterItemProvider == null ) {
            receiverParameterItemProvider = new ReceiverParameterItemProvider( this );
        }

        return receiverParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.VariableDeclarator} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected VariableDeclaratorItemProvider variableDeclaratorItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.VariableDeclarator}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createVariableDeclaratorAdapter() {
        if( variableDeclaratorItemProvider == null ) {
            variableDeclaratorItemProvider = new VariableDeclaratorItemProvider( this );
        }

        return variableDeclaratorItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.BlockComment} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BlockCommentItemProvider blockCommentItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.BlockComment}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBlockCommentAdapter() {
        if( blockCommentItemProvider == null ) {
            blockCommentItemProvider = new BlockCommentItemProvider( this );
        }

        return blockCommentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.JavadocComment} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected JavadocCommentItemProvider javadocCommentItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.JavadocComment}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createJavadocCommentAdapter() {
        if( javadocCommentItemProvider == null ) {
            javadocCommentItemProvider = new JavadocCommentItemProvider( this );
        }

        return javadocCommentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.LineComment} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LineCommentItemProvider lineCommentItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.LineComment}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLineCommentAdapter() {
        if( lineCommentItemProvider == null ) {
            lineCommentItemProvider = new LineCommentItemProvider( this );
        }

        return lineCommentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ArrayAccessExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ArrayAccessExprItemProvider arrayAccessExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ArrayAccessExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createArrayAccessExprAdapter() {
        if( arrayAccessExprItemProvider == null ) {
            arrayAccessExprItemProvider = new ArrayAccessExprItemProvider( this );
        }

        return arrayAccessExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ArrayCreationExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ArrayCreationExprItemProvider arrayCreationExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ArrayCreationExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createArrayCreationExprAdapter() {
        if( arrayCreationExprItemProvider == null ) {
            arrayCreationExprItemProvider = new ArrayCreationExprItemProvider( this );
        }

        return arrayCreationExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ArrayInitializerExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ArrayInitializerExprItemProvider arrayInitializerExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ArrayInitializerExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createArrayInitializerExprAdapter() {
        if( arrayInitializerExprItemProvider == null ) {
            arrayInitializerExprItemProvider = new ArrayInitializerExprItemProvider( this );
        }

        return arrayInitializerExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.AssignExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AssignExprItemProvider assignExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.AssignExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAssignExprAdapter() {
        if( assignExprItemProvider == null ) {
            assignExprItemProvider = new AssignExprItemProvider( this );
        }

        return assignExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.BinaryExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BinaryExprItemProvider binaryExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.BinaryExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBinaryExprAdapter() {
        if( binaryExprItemProvider == null ) {
            binaryExprItemProvider = new BinaryExprItemProvider( this );
        }

        return binaryExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.BooleanLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BooleanLiteralExprItemProvider booleanLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.BooleanLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBooleanLiteralExprAdapter() {
        if( booleanLiteralExprItemProvider == null ) {
            booleanLiteralExprItemProvider = new BooleanLiteralExprItemProvider( this );
        }

        return booleanLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.CastExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CastExprItemProvider castExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.CastExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCastExprAdapter() {
        if( castExprItemProvider == null ) {
            castExprItemProvider = new CastExprItemProvider( this );
        }

        return castExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.CharLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CharLiteralExprItemProvider charLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.CharLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCharLiteralExprAdapter() {
        if( charLiteralExprItemProvider == null ) {
            charLiteralExprItemProvider = new CharLiteralExprItemProvider( this );
        }

        return charLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ClassExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ClassExprItemProvider classExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ClassExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createClassExprAdapter() {
        if( classExprItemProvider == null ) {
            classExprItemProvider = new ClassExprItemProvider( this );
        }

        return classExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ConditionalExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ConditionalExprItemProvider conditionalExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ConditionalExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createConditionalExprAdapter() {
        if( conditionalExprItemProvider == null ) {
            conditionalExprItemProvider = new ConditionalExprItemProvider( this );
        }

        return conditionalExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.DoubleLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DoubleLiteralExprItemProvider doubleLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.DoubleLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createDoubleLiteralExprAdapter() {
        if( doubleLiteralExprItemProvider == null ) {
            doubleLiteralExprItemProvider = new DoubleLiteralExprItemProvider( this );
        }

        return doubleLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.EnclosedExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected EnclosedExprItemProvider enclosedExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.EnclosedExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createEnclosedExprAdapter() {
        if( enclosedExprItemProvider == null ) {
            enclosedExprItemProvider = new EnclosedExprItemProvider( this );
        }

        return enclosedExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.FieldAccessExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FieldAccessExprItemProvider fieldAccessExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.FieldAccessExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createFieldAccessExprAdapter() {
        if( fieldAccessExprItemProvider == null ) {
            fieldAccessExprItemProvider = new FieldAccessExprItemProvider( this );
        }

        return fieldAccessExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.InstanceOfExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InstanceOfExprItemProvider instanceOfExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.InstanceOfExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInstanceOfExprAdapter() {
        if( instanceOfExprItemProvider == null ) {
            instanceOfExprItemProvider = new InstanceOfExprItemProvider( this );
        }

        return instanceOfExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.IntegerLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IntegerLiteralExprItemProvider integerLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.IntegerLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createIntegerLiteralExprAdapter() {
        if( integerLiteralExprItemProvider == null ) {
            integerLiteralExprItemProvider = new IntegerLiteralExprItemProvider( this );
        }

        return integerLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.LambdaExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LambdaExprItemProvider lambdaExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.LambdaExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLambdaExprAdapter() {
        if( lambdaExprItemProvider == null ) {
            lambdaExprItemProvider = new LambdaExprItemProvider( this );
        }

        return lambdaExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.LongLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LongLiteralExprItemProvider longLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.LongLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLongLiteralExprAdapter() {
        if( longLiteralExprItemProvider == null ) {
            longLiteralExprItemProvider = new LongLiteralExprItemProvider( this );
        }

        return longLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.MarkerAnnotationExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected MarkerAnnotationExprItemProvider markerAnnotationExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.MarkerAnnotationExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createMarkerAnnotationExprAdapter() {
        if( markerAnnotationExprItemProvider == null ) {
            markerAnnotationExprItemProvider = new MarkerAnnotationExprItemProvider( this );
        }

        return markerAnnotationExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.MemberValuePair} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected MemberValuePairItemProvider memberValuePairItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.MemberValuePair}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createMemberValuePairAdapter() {
        if( memberValuePairItemProvider == null ) {
            memberValuePairItemProvider = new MemberValuePairItemProvider( this );
        }

        return memberValuePairItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.MethodCallExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected MethodCallExprItemProvider methodCallExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.MethodCallExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createMethodCallExprAdapter() {
        if( methodCallExprItemProvider == null ) {
            methodCallExprItemProvider = new MethodCallExprItemProvider( this );
        }

        return methodCallExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.MethodReferenceExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected MethodReferenceExprItemProvider methodReferenceExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.MethodReferenceExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createMethodReferenceExprAdapter() {
        if( methodReferenceExprItemProvider == null ) {
            methodReferenceExprItemProvider = new MethodReferenceExprItemProvider( this );
        }

        return methodReferenceExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.Name} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected NameItemProvider nameItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.Name}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createNameAdapter() {
        if( nameItemProvider == null ) {
            nameItemProvider = new NameItemProvider( this );
        }

        return nameItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.NameExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected NameExprItemProvider nameExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.NameExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createNameExprAdapter() {
        if( nameExprItemProvider == null ) {
            nameExprItemProvider = new NameExprItemProvider( this );
        }

        return nameExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.NormalAnnotationExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected NormalAnnotationExprItemProvider normalAnnotationExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.NormalAnnotationExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createNormalAnnotationExprAdapter() {
        if( normalAnnotationExprItemProvider == null ) {
            normalAnnotationExprItemProvider = new NormalAnnotationExprItemProvider( this );
        }

        return normalAnnotationExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.NullLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected NullLiteralExprItemProvider nullLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.NullLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createNullLiteralExprAdapter() {
        if( nullLiteralExprItemProvider == null ) {
            nullLiteralExprItemProvider = new NullLiteralExprItemProvider( this );
        }

        return nullLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ObjectCreationExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ObjectCreationExprItemProvider objectCreationExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ObjectCreationExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createObjectCreationExprAdapter() {
        if( objectCreationExprItemProvider == null ) {
            objectCreationExprItemProvider = new ObjectCreationExprItemProvider( this );
        }

        return objectCreationExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.PatternExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PatternExprItemProvider patternExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.PatternExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createPatternExprAdapter() {
        if( patternExprItemProvider == null ) {
            patternExprItemProvider = new PatternExprItemProvider( this );
        }

        return patternExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.SimpleName} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SimpleNameItemProvider simpleNameItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.SimpleName}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSimpleNameAdapter() {
        if( simpleNameItemProvider == null ) {
            simpleNameItemProvider = new SimpleNameItemProvider( this );
        }

        return simpleNameItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.SingleMemberAnnotationExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SingleMemberAnnotationExprItemProvider singleMemberAnnotationExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.SingleMemberAnnotationExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSingleMemberAnnotationExprAdapter() {
        if( singleMemberAnnotationExprItemProvider == null ) {
            singleMemberAnnotationExprItemProvider = new SingleMemberAnnotationExprItemProvider( this );
        }

        return singleMemberAnnotationExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.StringLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected StringLiteralExprItemProvider stringLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.StringLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createStringLiteralExprAdapter() {
        if( stringLiteralExprItemProvider == null ) {
            stringLiteralExprItemProvider = new StringLiteralExprItemProvider( this );
        }

        return stringLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.SuperExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SuperExprItemProvider superExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.SuperExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSuperExprAdapter() {
        if( superExprItemProvider == null ) {
            superExprItemProvider = new SuperExprItemProvider( this );
        }

        return superExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.SwitchExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SwitchExprItemProvider switchExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.SwitchExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSwitchExprAdapter() {
        if( switchExprItemProvider == null ) {
            switchExprItemProvider = new SwitchExprItemProvider( this );
        }

        return switchExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.TextBlockLiteralExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TextBlockLiteralExprItemProvider textBlockLiteralExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.TextBlockLiteralExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTextBlockLiteralExprAdapter() {
        if( textBlockLiteralExprItemProvider == null ) {
            textBlockLiteralExprItemProvider = new TextBlockLiteralExprItemProvider( this );
        }

        return textBlockLiteralExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ThisExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ThisExprItemProvider thisExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ThisExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createThisExprAdapter() {
        if( thisExprItemProvider == null ) {
            thisExprItemProvider = new ThisExprItemProvider( this );
        }

        return thisExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.TypeExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TypeExprItemProvider typeExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.TypeExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTypeExprAdapter() {
        if( typeExprItemProvider == null ) {
            typeExprItemProvider = new TypeExprItemProvider( this );
        }

        return typeExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.UnaryExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UnaryExprItemProvider unaryExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.UnaryExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createUnaryExprAdapter() {
        if( unaryExprItemProvider == null ) {
            unaryExprItemProvider = new UnaryExprItemProvider( this );
        }

        return unaryExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.VariableDeclarationExpr} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected VariableDeclarationExprItemProvider variableDeclarationExprItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.VariableDeclarationExpr}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createVariableDeclarationExprAdapter() {
        if( variableDeclarationExprItemProvider == null ) {
            variableDeclarationExprItemProvider = new VariableDeclarationExprItemProvider( this );
        }

        return variableDeclarationExprItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ModuleDeclaration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ModuleDeclarationItemProvider moduleDeclarationItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ModuleDeclaration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createModuleDeclarationAdapter() {
        if( moduleDeclarationItemProvider == null ) {
            moduleDeclarationItemProvider = new ModuleDeclarationItemProvider( this );
        }

        return moduleDeclarationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ModuleExportsDirective} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ModuleExportsDirectiveItemProvider moduleExportsDirectiveItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ModuleExportsDirective}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createModuleExportsDirectiveAdapter() {
        if( moduleExportsDirectiveItemProvider == null ) {
            moduleExportsDirectiveItemProvider = new ModuleExportsDirectiveItemProvider( this );
        }

        return moduleExportsDirectiveItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ModuleOpensDirective} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ModuleOpensDirectiveItemProvider moduleOpensDirectiveItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ModuleOpensDirective}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createModuleOpensDirectiveAdapter() {
        if( moduleOpensDirectiveItemProvider == null ) {
            moduleOpensDirectiveItemProvider = new ModuleOpensDirectiveItemProvider( this );
        }

        return moduleOpensDirectiveItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ModuleProvidesDirective} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ModuleProvidesDirectiveItemProvider moduleProvidesDirectiveItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ModuleProvidesDirective}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createModuleProvidesDirectiveAdapter() {
        if( moduleProvidesDirectiveItemProvider == null ) {
            moduleProvidesDirectiveItemProvider = new ModuleProvidesDirectiveItemProvider( this );
        }

        return moduleProvidesDirectiveItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ModuleRequiresDirective} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ModuleRequiresDirectiveItemProvider moduleRequiresDirectiveItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ModuleRequiresDirective}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createModuleRequiresDirectiveAdapter() {
        if( moduleRequiresDirectiveItemProvider == null ) {
            moduleRequiresDirectiveItemProvider = new ModuleRequiresDirectiveItemProvider( this );
        }

        return moduleRequiresDirectiveItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ModuleUsesDirective} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ModuleUsesDirectiveItemProvider moduleUsesDirectiveItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ModuleUsesDirective}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createModuleUsesDirectiveAdapter() {
        if( moduleUsesDirectiveItemProvider == null ) {
            moduleUsesDirectiveItemProvider = new ModuleUsesDirectiveItemProvider( this );
        }

        return moduleUsesDirectiveItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.AssertStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected AssertStmtItemProvider assertStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.AssertStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createAssertStmtAdapter() {
        if( assertStmtItemProvider == null ) {
            assertStmtItemProvider = new AssertStmtItemProvider( this );
        }

        return assertStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.BlockStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BlockStmtItemProvider blockStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.BlockStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBlockStmtAdapter() {
        if( blockStmtItemProvider == null ) {
            blockStmtItemProvider = new BlockStmtItemProvider( this );
        }

        return blockStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.BreakStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BreakStmtItemProvider breakStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.BreakStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createBreakStmtAdapter() {
        if( breakStmtItemProvider == null ) {
            breakStmtItemProvider = new BreakStmtItemProvider( this );
        }

        return breakStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.CatchClause} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CatchClauseItemProvider catchClauseItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.CatchClause}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCatchClauseAdapter() {
        if( catchClauseItemProvider == null ) {
            catchClauseItemProvider = new CatchClauseItemProvider( this );
        }

        return catchClauseItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ContinueStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ContinueStmtItemProvider continueStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ContinueStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createContinueStmtAdapter() {
        if( continueStmtItemProvider == null ) {
            continueStmtItemProvider = new ContinueStmtItemProvider( this );
        }

        return continueStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.DoStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DoStmtItemProvider doStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.DoStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createDoStmtAdapter() {
        if( doStmtItemProvider == null ) {
            doStmtItemProvider = new DoStmtItemProvider( this );
        }

        return doStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.EmptyStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected EmptyStmtItemProvider emptyStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.EmptyStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createEmptyStmtAdapter() {
        if( emptyStmtItemProvider == null ) {
            emptyStmtItemProvider = new EmptyStmtItemProvider( this );
        }

        return emptyStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ExplicitConstructorInvocationStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExplicitConstructorInvocationStmtItemProvider explicitConstructorInvocationStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ExplicitConstructorInvocationStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createExplicitConstructorInvocationStmtAdapter() {
        if( explicitConstructorInvocationStmtItemProvider == null ) {
            explicitConstructorInvocationStmtItemProvider = new ExplicitConstructorInvocationStmtItemProvider( this );
        }

        return explicitConstructorInvocationStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ExpressionStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExpressionStmtItemProvider expressionStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ExpressionStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createExpressionStmtAdapter() {
        if( expressionStmtItemProvider == null ) {
            expressionStmtItemProvider = new ExpressionStmtItemProvider( this );
        }

        return expressionStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ForEachStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ForEachStmtItemProvider forEachStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ForEachStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createForEachStmtAdapter() {
        if( forEachStmtItemProvider == null ) {
            forEachStmtItemProvider = new ForEachStmtItemProvider( this );
        }

        return forEachStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ForStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ForStmtItemProvider forStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ForStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createForStmtAdapter() {
        if( forStmtItemProvider == null ) {
            forStmtItemProvider = new ForStmtItemProvider( this );
        }

        return forStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.IfStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IfStmtItemProvider ifStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.IfStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createIfStmtAdapter() {
        if( ifStmtItemProvider == null ) {
            ifStmtItemProvider = new IfStmtItemProvider( this );
        }

        return ifStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.LabeledStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LabeledStmtItemProvider labeledStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.LabeledStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLabeledStmtAdapter() {
        if( labeledStmtItemProvider == null ) {
            labeledStmtItemProvider = new LabeledStmtItemProvider( this );
        }

        return labeledStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.LocalClassDeclarationStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LocalClassDeclarationStmtItemProvider localClassDeclarationStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.LocalClassDeclarationStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLocalClassDeclarationStmtAdapter() {
        if( localClassDeclarationStmtItemProvider == null ) {
            localClassDeclarationStmtItemProvider = new LocalClassDeclarationStmtItemProvider( this );
        }

        return localClassDeclarationStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ReturnStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ReturnStmtItemProvider returnStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ReturnStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createReturnStmtAdapter() {
        if( returnStmtItemProvider == null ) {
            returnStmtItemProvider = new ReturnStmtItemProvider( this );
        }

        return returnStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.Statement} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected StatementItemProvider statementItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.Statement}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createStatementAdapter() {
        if( statementItemProvider == null ) {
            statementItemProvider = new StatementItemProvider( this );
        }

        return statementItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.SwitchEntry} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SwitchEntryItemProvider switchEntryItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.SwitchEntry}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSwitchEntryAdapter() {
        if( switchEntryItemProvider == null ) {
            switchEntryItemProvider = new SwitchEntryItemProvider( this );
        }

        return switchEntryItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.SwitchStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SwitchStmtItemProvider switchStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.SwitchStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSwitchStmtAdapter() {
        if( switchStmtItemProvider == null ) {
            switchStmtItemProvider = new SwitchStmtItemProvider( this );
        }

        return switchStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.SynchronizedStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SynchronizedStmtItemProvider synchronizedStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.SynchronizedStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSynchronizedStmtAdapter() {
        if( synchronizedStmtItemProvider == null ) {
            synchronizedStmtItemProvider = new SynchronizedStmtItemProvider( this );
        }

        return synchronizedStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ThrowStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ThrowStmtItemProvider throwStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ThrowStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createThrowStmtAdapter() {
        if( throwStmtItemProvider == null ) {
            throwStmtItemProvider = new ThrowStmtItemProvider( this );
        }

        return throwStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.TryStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TryStmtItemProvider tryStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.TryStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTryStmtAdapter() {
        if( tryStmtItemProvider == null ) {
            tryStmtItemProvider = new TryStmtItemProvider( this );
        }

        return tryStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.WhileStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected WhileStmtItemProvider whileStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.WhileStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createWhileStmtAdapter() {
        if( whileStmtItemProvider == null ) {
            whileStmtItemProvider = new WhileStmtItemProvider( this );
        }

        return whileStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.YieldStmt} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected YieldStmtItemProvider yieldStmtItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.YieldStmt}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createYieldStmtAdapter() {
        if( yieldStmtItemProvider == null ) {
            yieldStmtItemProvider = new YieldStmtItemProvider( this );
        }

        return yieldStmtItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ArrayType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ArrayTypeItemProvider arrayTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ArrayType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createArrayTypeAdapter() {
        if( arrayTypeItemProvider == null ) {
            arrayTypeItemProvider = new ArrayTypeItemProvider( this );
        }

        return arrayTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.ClassOrInterfaceType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ClassOrInterfaceTypeItemProvider classOrInterfaceTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.ClassOrInterfaceType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createClassOrInterfaceTypeAdapter() {
        if( classOrInterfaceTypeItemProvider == null ) {
            classOrInterfaceTypeItemProvider = new ClassOrInterfaceTypeItemProvider( this );
        }

        return classOrInterfaceTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.IntersectionType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IntersectionTypeItemProvider intersectionTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.IntersectionType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createIntersectionTypeAdapter() {
        if( intersectionTypeItemProvider == null ) {
            intersectionTypeItemProvider = new IntersectionTypeItemProvider( this );
        }

        return intersectionTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.PrimitiveType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PrimitiveTypeItemProvider primitiveTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.PrimitiveType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createPrimitiveTypeAdapter() {
        if( primitiveTypeItemProvider == null ) {
            primitiveTypeItemProvider = new PrimitiveTypeItemProvider( this );
        }

        return primitiveTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.TypeParameter} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TypeParameterItemProvider typeParameterItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.TypeParameter}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createTypeParameterAdapter() {
        if( typeParameterItemProvider == null ) {
            typeParameterItemProvider = new TypeParameterItemProvider( this );
        }

        return typeParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.UnionType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UnionTypeItemProvider unionTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.UnionType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createUnionTypeAdapter() {
        if( unionTypeItemProvider == null ) {
            unionTypeItemProvider = new UnionTypeItemProvider( this );
        }

        return unionTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.UnknownType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UnknownTypeItemProvider unknownTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.UnknownType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createUnknownTypeAdapter() {
        if( unknownTypeItemProvider == null ) {
            unknownTypeItemProvider = new UnknownTypeItemProvider( this );
        }

        return unknownTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.VarType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected VarTypeItemProvider varTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.VarType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createVarTypeAdapter() {
        if( varTypeItemProvider == null ) {
            varTypeItemProvider = new VarTypeItemProvider( this );
        }

        return varTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.VoidType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected VoidTypeItemProvider voidTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.VoidType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createVoidTypeAdapter() {
        if( voidTypeItemProvider == null ) {
            voidTypeItemProvider = new VoidTypeItemProvider( this );
        }

        return voidTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link fr.centralesupelec.csd.ejava.WildcardType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected WildcardTypeItemProvider wildcardTypeItemProvider;

    /**
     * This creates an adapter for a {@link fr.centralesupelec.csd.ejava.WildcardType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createWildcardTypeAdapter() {
        if( wildcardTypeItemProvider == null ) {
            wildcardTypeItemProvider = new WildcardTypeItemProvider( this );
        }

        return wildcardTypeItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void setParentAdapterFactory( ComposedAdapterFactory parentAdapterFactory ) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public boolean isFactoryForType( Object type ) {
        return supportedTypes.contains( type ) || super.isFactoryForType( type );
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter adapt( Notifier notifier, Object type ) {
        return super.adapt( notifier, this );
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Object adapt( Object object, Object type ) {
        if( isFactoryForType( type ) ) {
            Object adapter = super.adapt( object, type );
            if( !( type instanceof Class< ? > ) || ( ( ( Class< ? > ) type ).isInstance( adapter ) ) ) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void addListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.addListener( notifyChangedListener );
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void removeListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.removeListener( notifyChangedListener );
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void fireNotifyChanged( Notification notification ) {
        changeNotifier.fireNotifyChanged( notification );

        if( parentAdapterFactory != null ) {
            parentAdapterFactory.fireNotifyChanged( notification );
        }
    }

    /**
     * This disposes all of the item providers created by this factory. 
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void dispose() {
        if( arrayCreationLevelItemProvider != null ) arrayCreationLevelItemProvider.dispose();
        if( compilationUnitItemProvider != null ) compilationUnitItemProvider.dispose();
        if( importDeclarationItemProvider != null ) importDeclarationItemProvider.dispose();
        if( packageDeclarationItemProvider != null ) packageDeclarationItemProvider.dispose();
        if( annotationDeclarationItemProvider != null ) annotationDeclarationItemProvider.dispose();
        if( annotationMemberDeclarationItemProvider != null ) annotationMemberDeclarationItemProvider.dispose();
        if( classOrInterfaceDeclarationItemProvider != null ) classOrInterfaceDeclarationItemProvider.dispose();
        if( constructorDeclarationItemProvider != null ) constructorDeclarationItemProvider.dispose();
        if( enumConstantDeclarationItemProvider != null ) enumConstantDeclarationItemProvider.dispose();
        if( enumDeclarationItemProvider != null ) enumDeclarationItemProvider.dispose();
        if( fieldDeclarationItemProvider != null ) fieldDeclarationItemProvider.dispose();
        if( initializerDeclarationItemProvider != null ) initializerDeclarationItemProvider.dispose();
        if( methodDeclarationItemProvider != null ) methodDeclarationItemProvider.dispose();
        if( parameterItemProvider != null ) parameterItemProvider.dispose();
        if( receiverParameterItemProvider != null ) receiverParameterItemProvider.dispose();
        if( variableDeclaratorItemProvider != null ) variableDeclaratorItemProvider.dispose();
        if( blockCommentItemProvider != null ) blockCommentItemProvider.dispose();
        if( javadocCommentItemProvider != null ) javadocCommentItemProvider.dispose();
        if( lineCommentItemProvider != null ) lineCommentItemProvider.dispose();
        if( arrayAccessExprItemProvider != null ) arrayAccessExprItemProvider.dispose();
        if( arrayCreationExprItemProvider != null ) arrayCreationExprItemProvider.dispose();
        if( arrayInitializerExprItemProvider != null ) arrayInitializerExprItemProvider.dispose();
        if( assignExprItemProvider != null ) assignExprItemProvider.dispose();
        if( binaryExprItemProvider != null ) binaryExprItemProvider.dispose();
        if( booleanLiteralExprItemProvider != null ) booleanLiteralExprItemProvider.dispose();
        if( castExprItemProvider != null ) castExprItemProvider.dispose();
        if( charLiteralExprItemProvider != null ) charLiteralExprItemProvider.dispose();
        if( classExprItemProvider != null ) classExprItemProvider.dispose();
        if( conditionalExprItemProvider != null ) conditionalExprItemProvider.dispose();
        if( doubleLiteralExprItemProvider != null ) doubleLiteralExprItemProvider.dispose();
        if( enclosedExprItemProvider != null ) enclosedExprItemProvider.dispose();
        if( fieldAccessExprItemProvider != null ) fieldAccessExprItemProvider.dispose();
        if( instanceOfExprItemProvider != null ) instanceOfExprItemProvider.dispose();
        if( integerLiteralExprItemProvider != null ) integerLiteralExprItemProvider.dispose();
        if( lambdaExprItemProvider != null ) lambdaExprItemProvider.dispose();
        if( longLiteralExprItemProvider != null ) longLiteralExprItemProvider.dispose();
        if( markerAnnotationExprItemProvider != null ) markerAnnotationExprItemProvider.dispose();
        if( memberValuePairItemProvider != null ) memberValuePairItemProvider.dispose();
        if( methodCallExprItemProvider != null ) methodCallExprItemProvider.dispose();
        if( methodReferenceExprItemProvider != null ) methodReferenceExprItemProvider.dispose();
        if( nameItemProvider != null ) nameItemProvider.dispose();
        if( nameExprItemProvider != null ) nameExprItemProvider.dispose();
        if( normalAnnotationExprItemProvider != null ) normalAnnotationExprItemProvider.dispose();
        if( nullLiteralExprItemProvider != null ) nullLiteralExprItemProvider.dispose();
        if( objectCreationExprItemProvider != null ) objectCreationExprItemProvider.dispose();
        if( patternExprItemProvider != null ) patternExprItemProvider.dispose();
        if( simpleNameItemProvider != null ) simpleNameItemProvider.dispose();
        if( singleMemberAnnotationExprItemProvider != null ) singleMemberAnnotationExprItemProvider.dispose();
        if( stringLiteralExprItemProvider != null ) stringLiteralExprItemProvider.dispose();
        if( superExprItemProvider != null ) superExprItemProvider.dispose();
        if( switchExprItemProvider != null ) switchExprItemProvider.dispose();
        if( textBlockLiteralExprItemProvider != null ) textBlockLiteralExprItemProvider.dispose();
        if( thisExprItemProvider != null ) thisExprItemProvider.dispose();
        if( typeExprItemProvider != null ) typeExprItemProvider.dispose();
        if( unaryExprItemProvider != null ) unaryExprItemProvider.dispose();
        if( variableDeclarationExprItemProvider != null ) variableDeclarationExprItemProvider.dispose();
        if( moduleDeclarationItemProvider != null ) moduleDeclarationItemProvider.dispose();
        if( moduleExportsDirectiveItemProvider != null ) moduleExportsDirectiveItemProvider.dispose();
        if( moduleOpensDirectiveItemProvider != null ) moduleOpensDirectiveItemProvider.dispose();
        if( moduleProvidesDirectiveItemProvider != null ) moduleProvidesDirectiveItemProvider.dispose();
        if( moduleRequiresDirectiveItemProvider != null ) moduleRequiresDirectiveItemProvider.dispose();
        if( moduleUsesDirectiveItemProvider != null ) moduleUsesDirectiveItemProvider.dispose();
        if( assertStmtItemProvider != null ) assertStmtItemProvider.dispose();
        if( blockStmtItemProvider != null ) blockStmtItemProvider.dispose();
        if( breakStmtItemProvider != null ) breakStmtItemProvider.dispose();
        if( catchClauseItemProvider != null ) catchClauseItemProvider.dispose();
        if( continueStmtItemProvider != null ) continueStmtItemProvider.dispose();
        if( doStmtItemProvider != null ) doStmtItemProvider.dispose();
        if( emptyStmtItemProvider != null ) emptyStmtItemProvider.dispose();
        if( explicitConstructorInvocationStmtItemProvider != null )
            explicitConstructorInvocationStmtItemProvider.dispose();
        if( expressionStmtItemProvider != null ) expressionStmtItemProvider.dispose();
        if( forEachStmtItemProvider != null ) forEachStmtItemProvider.dispose();
        if( forStmtItemProvider != null ) forStmtItemProvider.dispose();
        if( ifStmtItemProvider != null ) ifStmtItemProvider.dispose();
        if( labeledStmtItemProvider != null ) labeledStmtItemProvider.dispose();
        if( localClassDeclarationStmtItemProvider != null ) localClassDeclarationStmtItemProvider.dispose();
        if( returnStmtItemProvider != null ) returnStmtItemProvider.dispose();
        if( statementItemProvider != null ) statementItemProvider.dispose();
        if( switchEntryItemProvider != null ) switchEntryItemProvider.dispose();
        if( switchStmtItemProvider != null ) switchStmtItemProvider.dispose();
        if( synchronizedStmtItemProvider != null ) synchronizedStmtItemProvider.dispose();
        if( throwStmtItemProvider != null ) throwStmtItemProvider.dispose();
        if( tryStmtItemProvider != null ) tryStmtItemProvider.dispose();
        if( whileStmtItemProvider != null ) whileStmtItemProvider.dispose();
        if( yieldStmtItemProvider != null ) yieldStmtItemProvider.dispose();
        if( arrayTypeItemProvider != null ) arrayTypeItemProvider.dispose();
        if( classOrInterfaceTypeItemProvider != null ) classOrInterfaceTypeItemProvider.dispose();
        if( intersectionTypeItemProvider != null ) intersectionTypeItemProvider.dispose();
        if( primitiveTypeItemProvider != null ) primitiveTypeItemProvider.dispose();
        if( typeParameterItemProvider != null ) typeParameterItemProvider.dispose();
        if( unionTypeItemProvider != null ) unionTypeItemProvider.dispose();
        if( unknownTypeItemProvider != null ) unknownTypeItemProvider.dispose();
        if( varTypeItemProvider != null ) varTypeItemProvider.dispose();
        if( voidTypeItemProvider != null ) voidTypeItemProvider.dispose();
        if( wildcardTypeItemProvider != null ) wildcardTypeItemProvider.dispose();
    }

}
